# You can use RethinkDB with Docker
#
# https://hub.docker.com/_/rethinkdb/
#
# to easily setup your environment. To run locally you can do:
#
# docker run --rm -it -p 28015:28015 -p 29015:29015 -p 8080:8080 rethinkdb
